[package]
name = "actionkv"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.2.0"
crc = "1.7.0"
serde = "1.0.203"
serde_derive = "1.0.203"

[lib]
name = "libactionkv"
path = "src/lib.rs"

[[bin]]
name = "akv_mem"
path = "src/akv_mem.rs"
